package com.ruitx.formation.model;

public enum EventType {
    STUDENT_REGISTERED,
    STUDENT_ENROLLED,
    STUDENT_UNENROLLED,
    STUDENT_UPDATED,
    STUDENT_DELETED,
    COURSE_CREATED,
    COURSE_UPDATED,
    COURSE_DELETED,
    ENTRY_CREATED,
    ENTRY_UPDATED,
    ENTRY_DELETED,
    GET,
    POST,
    PUT,
    DELETE,
    CONTROLLER,
    ACTION
}
